
import { AttendanceRecord, Class, Student, loadAttendanceRecords, saveAttendanceRecords } from "./data";

// Format date to YYYY-MM-DD
export const formatDate = (date: Date): string => {
  return date.toISOString().split('T')[0];
};

// Get the current date formatted
export const getCurrentDate = (): string => {
  return formatDate(new Date());
};

// Create a new attendance record
export const createAttendanceRecord = (
  classId: string,
  date: string,
  presentStudents: string[]
): AttendanceRecord => {
  return {
    id: `attendance-${classId}-${date}`,
    classId,
    date,
    presentStudents,
  };
};

// Save an attendance record
export const saveAttendanceRecord = (record: AttendanceRecord): void => {
  const records = loadAttendanceRecords();
  
  // Check if a record for this class and date already exists
  const existingIndex = records.findIndex(
    (r) => r.classId === record.classId && r.date === record.date
  );
  
  if (existingIndex >= 0) {
    // Update existing record
    records[existingIndex] = record;
  } else {
    // Add new record
    records.push(record);
  }
  
  saveAttendanceRecords(records);
};

// Get an attendance record for a specific class and date
export const getAttendanceRecord = (
  classId: string,
  date: string
): AttendanceRecord | undefined => {
  const records = loadAttendanceRecords();
  return records.find((r) => r.classId === classId && r.date === date);
};

// Get all attendance records for a class
export const getClassAttendanceRecords = (classId: string): AttendanceRecord[] => {
  const records = loadAttendanceRecords();
  return records.filter((r) => r.classId === classId);
};

// Get all attendance records for a student
export const getStudentAttendanceRecords = (
  rollNumber: string,
  classId: string
): { date: string; present: boolean }[] => {
  const records = loadAttendanceRecords();
  const classRecords = records.filter((r) => r.classId === classId);
  
  return classRecords.map((record) => ({
    date: record.date,
    present: record.presentStudents.includes(rollNumber),
  }));
};

// Calculate attendance statistics for a student
export const calculateStudentAttendanceStats = (
  rollNumber: string,
  classId: string
): {
  totalClasses: number;
  present: number;
  absent: number;
  percentage: number;
} => {
  const records = getStudentAttendanceRecords(rollNumber, classId);
  const totalClasses = records.length;
  const present = records.filter((r) => r.present).length;
  const absent = totalClasses - present;
  const percentage = totalClasses > 0 ? (present / totalClasses) * 100 : 0;
  
  return {
    totalClasses,
    present,
    absent,
    percentage: Math.round(percentage * 100) / 100,
  };
};

// Get list of absentees for a specific class and date
export const getAbsenteesList = (
  classObj: Class,
  date: string
): Student[] => {
  const record = getAttendanceRecord(classObj.id, date);
  
  if (!record) {
    return classObj.students; // If no record, all students are considered absent
  }
  
  return classObj.students.filter(
    (student) => !record.presentStudents.includes(student.rollNumber)
  );
};

// Format attendance data for export/display
export const formatAttendanceReport = (
  classObj: Class,
  date: string
): string => {
  const record = getAttendanceRecord(classObj.id, date);
  const absentees = getAbsenteesList(classObj, date);
  const presentCount = record ? record.presentStudents.length : 0;
  const absentCount = classObj.students.length - presentCount;
  const presentPercentage = Math.round((presentCount / classObj.students.length) * 100);
  
  const dateObj = new Date(date);
  const formattedDate = dateObj.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  // Format the absentee list
  const absenteesList = absentees.map(student => 
    `${student.rollNumber} - ${student.name}`
  ).join('\n');
  
  return `*Attendance Report*
*Date:* ${formattedDate}
*Class:* ${classObj.name}
*Section:* ${classObj.section}
*Batch:* ${classObj.batch}

*Present:* ${presentCount}/${classObj.students.length} (${presentPercentage}%)
*Absent:* ${absentCount}/${classObj.students.length} (${100 - presentPercentage}%)

${absentees.length > 0 ? `*Absentees:*\n${absenteesList}` : '*All students present*'}

Generated by HighClass App`;
};

// Get formatted date string for display
export const getFormattedDateString = (date: string): string => {
  const dateObj = new Date(date);
  return dateObj.toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short', 
    day: 'numeric'
  });
};
