// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khfxfzsekuztaawwikqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZnhmenNla3V6dGFhd3dpa3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTYwMzAsImV4cCI6MjA1ODk3MjAzMH0.0yQvXNg87sCCuDvYQ8BQC7xG2u_6ft-D8VXIQTA93h4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);